---
- name: OpsTree solution
  hosts: "{{ host }}"
  tasks:
  - name: Downloading pip package
    get_url:
      url: https://bootstrap.pypa.io/get-pip.py
      dest: /tmp/
      mode: '0775'
  - name: Installing pip module and downloading boto3
    shell: |
      python /tmp/get-pip.py
      pip install boto3
  - name: Downloading S3 object to tmp folder
    aws_s3:
      bucket: test-s3-deploy-1
      object: /ganesh-logs/2020-06-01-17-17-13-8FBF8437906EBB60
      dest: /tmp/myfile.txt
      mode: get
